// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cms.proto

package com.zemoso.grpc.proto;

/**
 * Protobuf type {@code Blog}
 */
public  final class Blog extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Blog)
    BlogOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Blog.newBuilder() to construct.
  private Blog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Blog() {
    blogid_ = 0L;
    content_ = "";
    refuser_ = "";
    title_ = "";
    creationdate_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Blog(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            blogid_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            content_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            refuser_ = s;
            break;
          }
          case 34: {
            com.zemoso.grpc.proto.Commentlist.Builder subBuilder = null;
            if (comments_ != null) {
              subBuilder = comments_.toBuilder();
            }
            comments_ = input.readMessage(com.zemoso.grpc.proto.Commentlist.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(comments_);
              comments_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            title_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            creationdate_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.zemoso.grpc.proto.Cms.internal_static_Blog_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.zemoso.grpc.proto.Cms.internal_static_Blog_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.zemoso.grpc.proto.Blog.class, com.zemoso.grpc.proto.Blog.Builder.class);
  }

  public static final int BLOGID_FIELD_NUMBER = 1;
  private long blogid_;
  /**
   * <code>int64 blogid = 1;</code>
   */
  public long getBlogid() {
    return blogid_;
  }

  public static final int CONTENT_FIELD_NUMBER = 2;
  private volatile java.lang.Object content_;
  /**
   * <code>string content = 2;</code>
   */
  public java.lang.String getContent() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      content_ = s;
      return s;
    }
  }
  /**
   * <code>string content = 2;</code>
   */
  public com.google.protobuf.ByteString
      getContentBytes() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      content_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REFUSER_FIELD_NUMBER = 3;
  private volatile java.lang.Object refuser_;
  /**
   * <code>string refuser = 3;</code>
   */
  public java.lang.String getRefuser() {
    java.lang.Object ref = refuser_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      refuser_ = s;
      return s;
    }
  }
  /**
   * <code>string refuser = 3;</code>
   */
  public com.google.protobuf.ByteString
      getRefuserBytes() {
    java.lang.Object ref = refuser_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      refuser_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMMENTS_FIELD_NUMBER = 4;
  private com.zemoso.grpc.proto.Commentlist comments_;
  /**
   * <code>.Commentlist comments = 4;</code>
   */
  public boolean hasComments() {
    return comments_ != null;
  }
  /**
   * <code>.Commentlist comments = 4;</code>
   */
  public com.zemoso.grpc.proto.Commentlist getComments() {
    return comments_ == null ? com.zemoso.grpc.proto.Commentlist.getDefaultInstance() : comments_;
  }
  /**
   * <code>.Commentlist comments = 4;</code>
   */
  public com.zemoso.grpc.proto.CommentlistOrBuilder getCommentsOrBuilder() {
    return getComments();
  }

  public static final int TITLE_FIELD_NUMBER = 5;
  private volatile java.lang.Object title_;
  /**
   * <code>string title = 5;</code>
   */
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 5;</code>
   */
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATIONDATE_FIELD_NUMBER = 6;
  private volatile java.lang.Object creationdate_;
  /**
   * <code>string creationdate = 6;</code>
   */
  public java.lang.String getCreationdate() {
    java.lang.Object ref = creationdate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      creationdate_ = s;
      return s;
    }
  }
  /**
   * <code>string creationdate = 6;</code>
   */
  public com.google.protobuf.ByteString
      getCreationdateBytes() {
    java.lang.Object ref = creationdate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      creationdate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (blogid_ != 0L) {
      output.writeInt64(1, blogid_);
    }
    if (!getContentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, content_);
    }
    if (!getRefuserBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, refuser_);
    }
    if (comments_ != null) {
      output.writeMessage(4, getComments());
    }
    if (!getTitleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, title_);
    }
    if (!getCreationdateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, creationdate_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (blogid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, blogid_);
    }
    if (!getContentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, content_);
    }
    if (!getRefuserBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, refuser_);
    }
    if (comments_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getComments());
    }
    if (!getTitleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, title_);
    }
    if (!getCreationdateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, creationdate_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.zemoso.grpc.proto.Blog)) {
      return super.equals(obj);
    }
    com.zemoso.grpc.proto.Blog other = (com.zemoso.grpc.proto.Blog) obj;

    boolean result = true;
    result = result && (getBlogid()
        == other.getBlogid());
    result = result && getContent()
        .equals(other.getContent());
    result = result && getRefuser()
        .equals(other.getRefuser());
    result = result && (hasComments() == other.hasComments());
    if (hasComments()) {
      result = result && getComments()
          .equals(other.getComments());
    }
    result = result && getTitle()
        .equals(other.getTitle());
    result = result && getCreationdate()
        .equals(other.getCreationdate());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BLOGID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBlogid());
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    hash = (37 * hash) + REFUSER_FIELD_NUMBER;
    hash = (53 * hash) + getRefuser().hashCode();
    if (hasComments()) {
      hash = (37 * hash) + COMMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getComments().hashCode();
    }
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + CREATIONDATE_FIELD_NUMBER;
    hash = (53 * hash) + getCreationdate().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.zemoso.grpc.proto.Blog parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zemoso.grpc.proto.Blog parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zemoso.grpc.proto.Blog parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zemoso.grpc.proto.Blog parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zemoso.grpc.proto.Blog parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zemoso.grpc.proto.Blog parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zemoso.grpc.proto.Blog parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zemoso.grpc.proto.Blog parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zemoso.grpc.proto.Blog parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.zemoso.grpc.proto.Blog parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zemoso.grpc.proto.Blog parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zemoso.grpc.proto.Blog parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.zemoso.grpc.proto.Blog prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Blog}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Blog)
      com.zemoso.grpc.proto.BlogOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zemoso.grpc.proto.Cms.internal_static_Blog_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zemoso.grpc.proto.Cms.internal_static_Blog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zemoso.grpc.proto.Blog.class, com.zemoso.grpc.proto.Blog.Builder.class);
    }

    // Construct using com.zemoso.grpc.proto.Blog.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      blogid_ = 0L;

      content_ = "";

      refuser_ = "";

      if (commentsBuilder_ == null) {
        comments_ = null;
      } else {
        comments_ = null;
        commentsBuilder_ = null;
      }
      title_ = "";

      creationdate_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.zemoso.grpc.proto.Cms.internal_static_Blog_descriptor;
    }

    @java.lang.Override
    public com.zemoso.grpc.proto.Blog getDefaultInstanceForType() {
      return com.zemoso.grpc.proto.Blog.getDefaultInstance();
    }

    @java.lang.Override
    public com.zemoso.grpc.proto.Blog build() {
      com.zemoso.grpc.proto.Blog result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.zemoso.grpc.proto.Blog buildPartial() {
      com.zemoso.grpc.proto.Blog result = new com.zemoso.grpc.proto.Blog(this);
      result.blogid_ = blogid_;
      result.content_ = content_;
      result.refuser_ = refuser_;
      if (commentsBuilder_ == null) {
        result.comments_ = comments_;
      } else {
        result.comments_ = commentsBuilder_.build();
      }
      result.title_ = title_;
      result.creationdate_ = creationdate_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.zemoso.grpc.proto.Blog) {
        return mergeFrom((com.zemoso.grpc.proto.Blog)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.zemoso.grpc.proto.Blog other) {
      if (other == com.zemoso.grpc.proto.Blog.getDefaultInstance()) return this;
      if (other.getBlogid() != 0L) {
        setBlogid(other.getBlogid());
      }
      if (!other.getContent().isEmpty()) {
        content_ = other.content_;
        onChanged();
      }
      if (!other.getRefuser().isEmpty()) {
        refuser_ = other.refuser_;
        onChanged();
      }
      if (other.hasComments()) {
        mergeComments(other.getComments());
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        onChanged();
      }
      if (!other.getCreationdate().isEmpty()) {
        creationdate_ = other.creationdate_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.zemoso.grpc.proto.Blog parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.zemoso.grpc.proto.Blog) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long blogid_ ;
    /**
     * <code>int64 blogid = 1;</code>
     */
    public long getBlogid() {
      return blogid_;
    }
    /**
     * <code>int64 blogid = 1;</code>
     */
    public Builder setBlogid(long value) {
      
      blogid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 blogid = 1;</code>
     */
    public Builder clearBlogid() {
      
      blogid_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object content_ = "";
    /**
     * <code>string content = 2;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string content = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string content = 2;</code>
     */
    public Builder setContent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      content_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string content = 2;</code>
     */
    public Builder clearContent() {
      
      content_ = getDefaultInstance().getContent();
      onChanged();
      return this;
    }
    /**
     * <code>string content = 2;</code>
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      content_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object refuser_ = "";
    /**
     * <code>string refuser = 3;</code>
     */
    public java.lang.String getRefuser() {
      java.lang.Object ref = refuser_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        refuser_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string refuser = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRefuserBytes() {
      java.lang.Object ref = refuser_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        refuser_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string refuser = 3;</code>
     */
    public Builder setRefuser(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      refuser_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string refuser = 3;</code>
     */
    public Builder clearRefuser() {
      
      refuser_ = getDefaultInstance().getRefuser();
      onChanged();
      return this;
    }
    /**
     * <code>string refuser = 3;</code>
     */
    public Builder setRefuserBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      refuser_ = value;
      onChanged();
      return this;
    }

    private com.zemoso.grpc.proto.Commentlist comments_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.zemoso.grpc.proto.Commentlist, com.zemoso.grpc.proto.Commentlist.Builder, com.zemoso.grpc.proto.CommentlistOrBuilder> commentsBuilder_;
    /**
     * <code>.Commentlist comments = 4;</code>
     */
    public boolean hasComments() {
      return commentsBuilder_ != null || comments_ != null;
    }
    /**
     * <code>.Commentlist comments = 4;</code>
     */
    public com.zemoso.grpc.proto.Commentlist getComments() {
      if (commentsBuilder_ == null) {
        return comments_ == null ? com.zemoso.grpc.proto.Commentlist.getDefaultInstance() : comments_;
      } else {
        return commentsBuilder_.getMessage();
      }
    }
    /**
     * <code>.Commentlist comments = 4;</code>
     */
    public Builder setComments(com.zemoso.grpc.proto.Commentlist value) {
      if (commentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        comments_ = value;
        onChanged();
      } else {
        commentsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Commentlist comments = 4;</code>
     */
    public Builder setComments(
        com.zemoso.grpc.proto.Commentlist.Builder builderForValue) {
      if (commentsBuilder_ == null) {
        comments_ = builderForValue.build();
        onChanged();
      } else {
        commentsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Commentlist comments = 4;</code>
     */
    public Builder mergeComments(com.zemoso.grpc.proto.Commentlist value) {
      if (commentsBuilder_ == null) {
        if (comments_ != null) {
          comments_ =
            com.zemoso.grpc.proto.Commentlist.newBuilder(comments_).mergeFrom(value).buildPartial();
        } else {
          comments_ = value;
        }
        onChanged();
      } else {
        commentsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Commentlist comments = 4;</code>
     */
    public Builder clearComments() {
      if (commentsBuilder_ == null) {
        comments_ = null;
        onChanged();
      } else {
        comments_ = null;
        commentsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Commentlist comments = 4;</code>
     */
    public com.zemoso.grpc.proto.Commentlist.Builder getCommentsBuilder() {
      
      onChanged();
      return getCommentsFieldBuilder().getBuilder();
    }
    /**
     * <code>.Commentlist comments = 4;</code>
     */
    public com.zemoso.grpc.proto.CommentlistOrBuilder getCommentsOrBuilder() {
      if (commentsBuilder_ != null) {
        return commentsBuilder_.getMessageOrBuilder();
      } else {
        return comments_ == null ?
            com.zemoso.grpc.proto.Commentlist.getDefaultInstance() : comments_;
      }
    }
    /**
     * <code>.Commentlist comments = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.zemoso.grpc.proto.Commentlist, com.zemoso.grpc.proto.Commentlist.Builder, com.zemoso.grpc.proto.CommentlistOrBuilder> 
        getCommentsFieldBuilder() {
      if (commentsBuilder_ == null) {
        commentsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.zemoso.grpc.proto.Commentlist, com.zemoso.grpc.proto.Commentlist.Builder, com.zemoso.grpc.proto.CommentlistOrBuilder>(
                getComments(),
                getParentForChildren(),
                isClean());
        comments_ = null;
      }
      return commentsBuilder_;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 5;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 5;</code>
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      title_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 5;</code>
     */
    public Builder clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
      onChanged();
      return this;
    }
    /**
     * <code>string title = 5;</code>
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      title_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object creationdate_ = "";
    /**
     * <code>string creationdate = 6;</code>
     */
    public java.lang.String getCreationdate() {
      java.lang.Object ref = creationdate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        creationdate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string creationdate = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCreationdateBytes() {
      java.lang.Object ref = creationdate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        creationdate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string creationdate = 6;</code>
     */
    public Builder setCreationdate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      creationdate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string creationdate = 6;</code>
     */
    public Builder clearCreationdate() {
      
      creationdate_ = getDefaultInstance().getCreationdate();
      onChanged();
      return this;
    }
    /**
     * <code>string creationdate = 6;</code>
     */
    public Builder setCreationdateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      creationdate_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Blog)
  }

  // @@protoc_insertion_point(class_scope:Blog)
  private static final com.zemoso.grpc.proto.Blog DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.zemoso.grpc.proto.Blog();
  }

  public static com.zemoso.grpc.proto.Blog getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Blog>
      PARSER = new com.google.protobuf.AbstractParser<Blog>() {
    @java.lang.Override
    public Blog parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Blog(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Blog> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Blog> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.zemoso.grpc.proto.Blog getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

