// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cms.proto

package com.zemoso.grpc.proto;

/**
 * Protobuf type {@code Bloglist}
 */
public  final class Bloglist extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Bloglist)
    BloglistOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Bloglist.newBuilder() to construct.
  private Bloglist(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Bloglist() {
    bloglistid_ = 0L;
    blogs_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Bloglist(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            bloglistid_ = input.readInt64();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              blogs_ = new java.util.ArrayList<com.zemoso.grpc.proto.Blog>();
              mutable_bitField0_ |= 0x00000002;
            }
            blogs_.add(
                input.readMessage(com.zemoso.grpc.proto.Blog.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        blogs_ = java.util.Collections.unmodifiableList(blogs_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.zemoso.grpc.proto.Cms.internal_static_Bloglist_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.zemoso.grpc.proto.Cms.internal_static_Bloglist_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.zemoso.grpc.proto.Bloglist.class, com.zemoso.grpc.proto.Bloglist.Builder.class);
  }

  private int bitField0_;
  public static final int BLOGLISTID_FIELD_NUMBER = 1;
  private long bloglistid_;
  /**
   * <code>int64 bloglistid = 1;</code>
   */
  public long getBloglistid() {
    return bloglistid_;
  }

  public static final int BLOGS_FIELD_NUMBER = 2;
  private java.util.List<com.zemoso.grpc.proto.Blog> blogs_;
  /**
   * <code>repeated .Blog blogs = 2;</code>
   */
  public java.util.List<com.zemoso.grpc.proto.Blog> getBlogsList() {
    return blogs_;
  }
  /**
   * <code>repeated .Blog blogs = 2;</code>
   */
  public java.util.List<? extends com.zemoso.grpc.proto.BlogOrBuilder> 
      getBlogsOrBuilderList() {
    return blogs_;
  }
  /**
   * <code>repeated .Blog blogs = 2;</code>
   */
  public int getBlogsCount() {
    return blogs_.size();
  }
  /**
   * <code>repeated .Blog blogs = 2;</code>
   */
  public com.zemoso.grpc.proto.Blog getBlogs(int index) {
    return blogs_.get(index);
  }
  /**
   * <code>repeated .Blog blogs = 2;</code>
   */
  public com.zemoso.grpc.proto.BlogOrBuilder getBlogsOrBuilder(
      int index) {
    return blogs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (bloglistid_ != 0L) {
      output.writeInt64(1, bloglistid_);
    }
    for (int i = 0; i < blogs_.size(); i++) {
      output.writeMessage(2, blogs_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (bloglistid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, bloglistid_);
    }
    for (int i = 0; i < blogs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, blogs_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.zemoso.grpc.proto.Bloglist)) {
      return super.equals(obj);
    }
    com.zemoso.grpc.proto.Bloglist other = (com.zemoso.grpc.proto.Bloglist) obj;

    boolean result = true;
    result = result && (getBloglistid()
        == other.getBloglistid());
    result = result && getBlogsList()
        .equals(other.getBlogsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BLOGLISTID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBloglistid());
    if (getBlogsCount() > 0) {
      hash = (37 * hash) + BLOGS_FIELD_NUMBER;
      hash = (53 * hash) + getBlogsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.zemoso.grpc.proto.Bloglist parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zemoso.grpc.proto.Bloglist parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zemoso.grpc.proto.Bloglist parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zemoso.grpc.proto.Bloglist parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zemoso.grpc.proto.Bloglist parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zemoso.grpc.proto.Bloglist parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zemoso.grpc.proto.Bloglist parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zemoso.grpc.proto.Bloglist parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zemoso.grpc.proto.Bloglist parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.zemoso.grpc.proto.Bloglist parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zemoso.grpc.proto.Bloglist parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zemoso.grpc.proto.Bloglist parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.zemoso.grpc.proto.Bloglist prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Bloglist}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Bloglist)
      com.zemoso.grpc.proto.BloglistOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zemoso.grpc.proto.Cms.internal_static_Bloglist_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zemoso.grpc.proto.Cms.internal_static_Bloglist_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zemoso.grpc.proto.Bloglist.class, com.zemoso.grpc.proto.Bloglist.Builder.class);
    }

    // Construct using com.zemoso.grpc.proto.Bloglist.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBlogsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bloglistid_ = 0L;

      if (blogsBuilder_ == null) {
        blogs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        blogsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.zemoso.grpc.proto.Cms.internal_static_Bloglist_descriptor;
    }

    @java.lang.Override
    public com.zemoso.grpc.proto.Bloglist getDefaultInstanceForType() {
      return com.zemoso.grpc.proto.Bloglist.getDefaultInstance();
    }

    @java.lang.Override
    public com.zemoso.grpc.proto.Bloglist build() {
      com.zemoso.grpc.proto.Bloglist result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.zemoso.grpc.proto.Bloglist buildPartial() {
      com.zemoso.grpc.proto.Bloglist result = new com.zemoso.grpc.proto.Bloglist(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.bloglistid_ = bloglistid_;
      if (blogsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          blogs_ = java.util.Collections.unmodifiableList(blogs_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.blogs_ = blogs_;
      } else {
        result.blogs_ = blogsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.zemoso.grpc.proto.Bloglist) {
        return mergeFrom((com.zemoso.grpc.proto.Bloglist)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.zemoso.grpc.proto.Bloglist other) {
      if (other == com.zemoso.grpc.proto.Bloglist.getDefaultInstance()) return this;
      if (other.getBloglistid() != 0L) {
        setBloglistid(other.getBloglistid());
      }
      if (blogsBuilder_ == null) {
        if (!other.blogs_.isEmpty()) {
          if (blogs_.isEmpty()) {
            blogs_ = other.blogs_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureBlogsIsMutable();
            blogs_.addAll(other.blogs_);
          }
          onChanged();
        }
      } else {
        if (!other.blogs_.isEmpty()) {
          if (blogsBuilder_.isEmpty()) {
            blogsBuilder_.dispose();
            blogsBuilder_ = null;
            blogs_ = other.blogs_;
            bitField0_ = (bitField0_ & ~0x00000002);
            blogsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBlogsFieldBuilder() : null;
          } else {
            blogsBuilder_.addAllMessages(other.blogs_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.zemoso.grpc.proto.Bloglist parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.zemoso.grpc.proto.Bloglist) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long bloglistid_ ;
    /**
     * <code>int64 bloglistid = 1;</code>
     */
    public long getBloglistid() {
      return bloglistid_;
    }
    /**
     * <code>int64 bloglistid = 1;</code>
     */
    public Builder setBloglistid(long value) {
      
      bloglistid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 bloglistid = 1;</code>
     */
    public Builder clearBloglistid() {
      
      bloglistid_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<com.zemoso.grpc.proto.Blog> blogs_ =
      java.util.Collections.emptyList();
    private void ensureBlogsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        blogs_ = new java.util.ArrayList<com.zemoso.grpc.proto.Blog>(blogs_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.zemoso.grpc.proto.Blog, com.zemoso.grpc.proto.Blog.Builder, com.zemoso.grpc.proto.BlogOrBuilder> blogsBuilder_;

    /**
     * <code>repeated .Blog blogs = 2;</code>
     */
    public java.util.List<com.zemoso.grpc.proto.Blog> getBlogsList() {
      if (blogsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(blogs_);
      } else {
        return blogsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Blog blogs = 2;</code>
     */
    public int getBlogsCount() {
      if (blogsBuilder_ == null) {
        return blogs_.size();
      } else {
        return blogsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Blog blogs = 2;</code>
     */
    public com.zemoso.grpc.proto.Blog getBlogs(int index) {
      if (blogsBuilder_ == null) {
        return blogs_.get(index);
      } else {
        return blogsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Blog blogs = 2;</code>
     */
    public Builder setBlogs(
        int index, com.zemoso.grpc.proto.Blog value) {
      if (blogsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBlogsIsMutable();
        blogs_.set(index, value);
        onChanged();
      } else {
        blogsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Blog blogs = 2;</code>
     */
    public Builder setBlogs(
        int index, com.zemoso.grpc.proto.Blog.Builder builderForValue) {
      if (blogsBuilder_ == null) {
        ensureBlogsIsMutable();
        blogs_.set(index, builderForValue.build());
        onChanged();
      } else {
        blogsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Blog blogs = 2;</code>
     */
    public Builder addBlogs(com.zemoso.grpc.proto.Blog value) {
      if (blogsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBlogsIsMutable();
        blogs_.add(value);
        onChanged();
      } else {
        blogsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Blog blogs = 2;</code>
     */
    public Builder addBlogs(
        int index, com.zemoso.grpc.proto.Blog value) {
      if (blogsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBlogsIsMutable();
        blogs_.add(index, value);
        onChanged();
      } else {
        blogsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Blog blogs = 2;</code>
     */
    public Builder addBlogs(
        com.zemoso.grpc.proto.Blog.Builder builderForValue) {
      if (blogsBuilder_ == null) {
        ensureBlogsIsMutable();
        blogs_.add(builderForValue.build());
        onChanged();
      } else {
        blogsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Blog blogs = 2;</code>
     */
    public Builder addBlogs(
        int index, com.zemoso.grpc.proto.Blog.Builder builderForValue) {
      if (blogsBuilder_ == null) {
        ensureBlogsIsMutable();
        blogs_.add(index, builderForValue.build());
        onChanged();
      } else {
        blogsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Blog blogs = 2;</code>
     */
    public Builder addAllBlogs(
        java.lang.Iterable<? extends com.zemoso.grpc.proto.Blog> values) {
      if (blogsBuilder_ == null) {
        ensureBlogsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, blogs_);
        onChanged();
      } else {
        blogsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Blog blogs = 2;</code>
     */
    public Builder clearBlogs() {
      if (blogsBuilder_ == null) {
        blogs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        blogsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Blog blogs = 2;</code>
     */
    public Builder removeBlogs(int index) {
      if (blogsBuilder_ == null) {
        ensureBlogsIsMutable();
        blogs_.remove(index);
        onChanged();
      } else {
        blogsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Blog blogs = 2;</code>
     */
    public com.zemoso.grpc.proto.Blog.Builder getBlogsBuilder(
        int index) {
      return getBlogsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Blog blogs = 2;</code>
     */
    public com.zemoso.grpc.proto.BlogOrBuilder getBlogsOrBuilder(
        int index) {
      if (blogsBuilder_ == null) {
        return blogs_.get(index);  } else {
        return blogsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Blog blogs = 2;</code>
     */
    public java.util.List<? extends com.zemoso.grpc.proto.BlogOrBuilder> 
         getBlogsOrBuilderList() {
      if (blogsBuilder_ != null) {
        return blogsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(blogs_);
      }
    }
    /**
     * <code>repeated .Blog blogs = 2;</code>
     */
    public com.zemoso.grpc.proto.Blog.Builder addBlogsBuilder() {
      return getBlogsFieldBuilder().addBuilder(
          com.zemoso.grpc.proto.Blog.getDefaultInstance());
    }
    /**
     * <code>repeated .Blog blogs = 2;</code>
     */
    public com.zemoso.grpc.proto.Blog.Builder addBlogsBuilder(
        int index) {
      return getBlogsFieldBuilder().addBuilder(
          index, com.zemoso.grpc.proto.Blog.getDefaultInstance());
    }
    /**
     * <code>repeated .Blog blogs = 2;</code>
     */
    public java.util.List<com.zemoso.grpc.proto.Blog.Builder> 
         getBlogsBuilderList() {
      return getBlogsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.zemoso.grpc.proto.Blog, com.zemoso.grpc.proto.Blog.Builder, com.zemoso.grpc.proto.BlogOrBuilder> 
        getBlogsFieldBuilder() {
      if (blogsBuilder_ == null) {
        blogsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.zemoso.grpc.proto.Blog, com.zemoso.grpc.proto.Blog.Builder, com.zemoso.grpc.proto.BlogOrBuilder>(
                blogs_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        blogs_ = null;
      }
      return blogsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Bloglist)
  }

  // @@protoc_insertion_point(class_scope:Bloglist)
  private static final com.zemoso.grpc.proto.Bloglist DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.zemoso.grpc.proto.Bloglist();
  }

  public static com.zemoso.grpc.proto.Bloglist getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Bloglist>
      PARSER = new com.google.protobuf.AbstractParser<Bloglist>() {
    @java.lang.Override
    public Bloglist parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Bloglist(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Bloglist> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Bloglist> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.zemoso.grpc.proto.Bloglist getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

