// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cms.proto

package com.zemoso.grpc.proto;

public interface BlogOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Blog)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 blogid = 1;</code>
   */
  long getBlogid();

  /**
   * <code>string content = 2;</code>
   */
  java.lang.String getContent();
  /**
   * <code>string content = 2;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>string refuser = 3;</code>
   */
  java.lang.String getRefuser();
  /**
   * <code>string refuser = 3;</code>
   */
  com.google.protobuf.ByteString
      getRefuserBytes();

  /**
   * <code>.Commentlist comments = 4;</code>
   */
  boolean hasComments();
  /**
   * <code>.Commentlist comments = 4;</code>
   */
  com.zemoso.grpc.proto.Commentlist getComments();
  /**
   * <code>.Commentlist comments = 4;</code>
   */
  com.zemoso.grpc.proto.CommentlistOrBuilder getCommentsOrBuilder();

  /**
   * <code>string title = 5;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 5;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string creationdate = 6;</code>
   */
  java.lang.String getCreationdate();
  /**
   * <code>string creationdate = 6;</code>
   */
  com.google.protobuf.ByteString
      getCreationdateBytes();
}
