// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cms.proto

package com.zemoso.grpc.proto;

/**
 * Protobuf type {@code Comment}
 */
public  final class Comment extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Comment)
    CommentOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Comment.newBuilder() to construct.
  private Comment(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Comment() {
    commentsid_ = 0L;
    content_ = "";
    commentsdate_ = "";
    blogid_ = 0L;
    refuser_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Comment(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            commentsid_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            content_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            commentsdate_ = s;
            break;
          }
          case 32: {

            blogid_ = input.readInt64();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            refuser_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.zemoso.grpc.proto.Cms.internal_static_Comment_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.zemoso.grpc.proto.Cms.internal_static_Comment_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.zemoso.grpc.proto.Comment.class, com.zemoso.grpc.proto.Comment.Builder.class);
  }

  public static final int COMMENTSID_FIELD_NUMBER = 1;
  private long commentsid_;
  /**
   * <code>int64 commentsid = 1;</code>
   */
  public long getCommentsid() {
    return commentsid_;
  }

  public static final int CONTENT_FIELD_NUMBER = 2;
  private volatile java.lang.Object content_;
  /**
   * <code>string content = 2;</code>
   */
  public java.lang.String getContent() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      content_ = s;
      return s;
    }
  }
  /**
   * <code>string content = 2;</code>
   */
  public com.google.protobuf.ByteString
      getContentBytes() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      content_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMMENTSDATE_FIELD_NUMBER = 3;
  private volatile java.lang.Object commentsdate_;
  /**
   * <code>string commentsdate = 3;</code>
   */
  public java.lang.String getCommentsdate() {
    java.lang.Object ref = commentsdate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      commentsdate_ = s;
      return s;
    }
  }
  /**
   * <code>string commentsdate = 3;</code>
   */
  public com.google.protobuf.ByteString
      getCommentsdateBytes() {
    java.lang.Object ref = commentsdate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      commentsdate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BLOGID_FIELD_NUMBER = 4;
  private long blogid_;
  /**
   * <code>int64 blogid = 4;</code>
   */
  public long getBlogid() {
    return blogid_;
  }

  public static final int REFUSER_FIELD_NUMBER = 5;
  private volatile java.lang.Object refuser_;
  /**
   * <code>string refuser = 5;</code>
   */
  public java.lang.String getRefuser() {
    java.lang.Object ref = refuser_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      refuser_ = s;
      return s;
    }
  }
  /**
   * <code>string refuser = 5;</code>
   */
  public com.google.protobuf.ByteString
      getRefuserBytes() {
    java.lang.Object ref = refuser_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      refuser_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (commentsid_ != 0L) {
      output.writeInt64(1, commentsid_);
    }
    if (!getContentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, content_);
    }
    if (!getCommentsdateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, commentsdate_);
    }
    if (blogid_ != 0L) {
      output.writeInt64(4, blogid_);
    }
    if (!getRefuserBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, refuser_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (commentsid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, commentsid_);
    }
    if (!getContentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, content_);
    }
    if (!getCommentsdateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, commentsdate_);
    }
    if (blogid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, blogid_);
    }
    if (!getRefuserBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, refuser_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.zemoso.grpc.proto.Comment)) {
      return super.equals(obj);
    }
    com.zemoso.grpc.proto.Comment other = (com.zemoso.grpc.proto.Comment) obj;

    boolean result = true;
    result = result && (getCommentsid()
        == other.getCommentsid());
    result = result && getContent()
        .equals(other.getContent());
    result = result && getCommentsdate()
        .equals(other.getCommentsdate());
    result = result && (getBlogid()
        == other.getBlogid());
    result = result && getRefuser()
        .equals(other.getRefuser());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COMMENTSID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCommentsid());
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    hash = (37 * hash) + COMMENTSDATE_FIELD_NUMBER;
    hash = (53 * hash) + getCommentsdate().hashCode();
    hash = (37 * hash) + BLOGID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBlogid());
    hash = (37 * hash) + REFUSER_FIELD_NUMBER;
    hash = (53 * hash) + getRefuser().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.zemoso.grpc.proto.Comment parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zemoso.grpc.proto.Comment parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zemoso.grpc.proto.Comment parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zemoso.grpc.proto.Comment parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zemoso.grpc.proto.Comment parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zemoso.grpc.proto.Comment parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zemoso.grpc.proto.Comment parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zemoso.grpc.proto.Comment parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zemoso.grpc.proto.Comment parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.zemoso.grpc.proto.Comment parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zemoso.grpc.proto.Comment parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zemoso.grpc.proto.Comment parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.zemoso.grpc.proto.Comment prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Comment}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Comment)
      com.zemoso.grpc.proto.CommentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zemoso.grpc.proto.Cms.internal_static_Comment_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zemoso.grpc.proto.Cms.internal_static_Comment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zemoso.grpc.proto.Comment.class, com.zemoso.grpc.proto.Comment.Builder.class);
    }

    // Construct using com.zemoso.grpc.proto.Comment.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      commentsid_ = 0L;

      content_ = "";

      commentsdate_ = "";

      blogid_ = 0L;

      refuser_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.zemoso.grpc.proto.Cms.internal_static_Comment_descriptor;
    }

    @java.lang.Override
    public com.zemoso.grpc.proto.Comment getDefaultInstanceForType() {
      return com.zemoso.grpc.proto.Comment.getDefaultInstance();
    }

    @java.lang.Override
    public com.zemoso.grpc.proto.Comment build() {
      com.zemoso.grpc.proto.Comment result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.zemoso.grpc.proto.Comment buildPartial() {
      com.zemoso.grpc.proto.Comment result = new com.zemoso.grpc.proto.Comment(this);
      result.commentsid_ = commentsid_;
      result.content_ = content_;
      result.commentsdate_ = commentsdate_;
      result.blogid_ = blogid_;
      result.refuser_ = refuser_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.zemoso.grpc.proto.Comment) {
        return mergeFrom((com.zemoso.grpc.proto.Comment)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.zemoso.grpc.proto.Comment other) {
      if (other == com.zemoso.grpc.proto.Comment.getDefaultInstance()) return this;
      if (other.getCommentsid() != 0L) {
        setCommentsid(other.getCommentsid());
      }
      if (!other.getContent().isEmpty()) {
        content_ = other.content_;
        onChanged();
      }
      if (!other.getCommentsdate().isEmpty()) {
        commentsdate_ = other.commentsdate_;
        onChanged();
      }
      if (other.getBlogid() != 0L) {
        setBlogid(other.getBlogid());
      }
      if (!other.getRefuser().isEmpty()) {
        refuser_ = other.refuser_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.zemoso.grpc.proto.Comment parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.zemoso.grpc.proto.Comment) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long commentsid_ ;
    /**
     * <code>int64 commentsid = 1;</code>
     */
    public long getCommentsid() {
      return commentsid_;
    }
    /**
     * <code>int64 commentsid = 1;</code>
     */
    public Builder setCommentsid(long value) {
      
      commentsid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 commentsid = 1;</code>
     */
    public Builder clearCommentsid() {
      
      commentsid_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object content_ = "";
    /**
     * <code>string content = 2;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string content = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string content = 2;</code>
     */
    public Builder setContent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      content_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string content = 2;</code>
     */
    public Builder clearContent() {
      
      content_ = getDefaultInstance().getContent();
      onChanged();
      return this;
    }
    /**
     * <code>string content = 2;</code>
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      content_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object commentsdate_ = "";
    /**
     * <code>string commentsdate = 3;</code>
     */
    public java.lang.String getCommentsdate() {
      java.lang.Object ref = commentsdate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        commentsdate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string commentsdate = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCommentsdateBytes() {
      java.lang.Object ref = commentsdate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commentsdate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string commentsdate = 3;</code>
     */
    public Builder setCommentsdate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      commentsdate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string commentsdate = 3;</code>
     */
    public Builder clearCommentsdate() {
      
      commentsdate_ = getDefaultInstance().getCommentsdate();
      onChanged();
      return this;
    }
    /**
     * <code>string commentsdate = 3;</code>
     */
    public Builder setCommentsdateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      commentsdate_ = value;
      onChanged();
      return this;
    }

    private long blogid_ ;
    /**
     * <code>int64 blogid = 4;</code>
     */
    public long getBlogid() {
      return blogid_;
    }
    /**
     * <code>int64 blogid = 4;</code>
     */
    public Builder setBlogid(long value) {
      
      blogid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 blogid = 4;</code>
     */
    public Builder clearBlogid() {
      
      blogid_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object refuser_ = "";
    /**
     * <code>string refuser = 5;</code>
     */
    public java.lang.String getRefuser() {
      java.lang.Object ref = refuser_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        refuser_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string refuser = 5;</code>
     */
    public com.google.protobuf.ByteString
        getRefuserBytes() {
      java.lang.Object ref = refuser_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        refuser_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string refuser = 5;</code>
     */
    public Builder setRefuser(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      refuser_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string refuser = 5;</code>
     */
    public Builder clearRefuser() {
      
      refuser_ = getDefaultInstance().getRefuser();
      onChanged();
      return this;
    }
    /**
     * <code>string refuser = 5;</code>
     */
    public Builder setRefuserBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      refuser_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Comment)
  }

  // @@protoc_insertion_point(class_scope:Comment)
  private static final com.zemoso.grpc.proto.Comment DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.zemoso.grpc.proto.Comment();
  }

  public static com.zemoso.grpc.proto.Comment getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Comment>
      PARSER = new com.google.protobuf.AbstractParser<Comment>() {
    @java.lang.Override
    public Comment parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Comment(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Comment> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Comment> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.zemoso.grpc.proto.Comment getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

