// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cms.proto

package com.zemoso.grpc.proto;

public interface CommentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Comment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 commentsid = 1;</code>
   */
  long getCommentsid();

  /**
   * <code>string content = 2;</code>
   */
  java.lang.String getContent();
  /**
   * <code>string content = 2;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>string commentsdate = 3;</code>
   */
  java.lang.String getCommentsdate();
  /**
   * <code>string commentsdate = 3;</code>
   */
  com.google.protobuf.ByteString
      getCommentsdateBytes();

  /**
   * <code>int64 blogid = 4;</code>
   */
  long getBlogid();

  /**
   * <code>string refuser = 5;</code>
   */
  java.lang.String getRefuser();
  /**
   * <code>string refuser = 5;</code>
   */
  com.google.protobuf.ByteString
      getRefuserBytes();
}
