// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cms.proto

package com.zemoso.grpc.proto;

public interface DeletePostOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeletePost)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 blogid = 1;</code>
   */
  long getBlogid();
}
