// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cms.proto

package com.zemoso.grpc.proto;

public interface GrpcsocialuserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Grpcsocialuser)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 userid = 1;</code>
   */
  long getUserid();

  /**
   * <code>string email = 2;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 2;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string firstName = 3;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>string firstName = 3;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string lastName = 4;</code>
   */
  java.lang.String getLastName();
  /**
   * <code>string lastName = 4;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string token = 5;</code>
   */
  java.lang.String getToken();
  /**
   * <code>string token = 5;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
