// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cms.proto

package com.zemoso.grpc.proto;

public interface LogincmsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Logincms)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 responsecode = 1;</code>
   */
  int getResponsecode();

  /**
   * <code>string responsemessage = 2;</code>
   */
  java.lang.String getResponsemessage();
  /**
   * <code>string responsemessage = 2;</code>
   */
  com.google.protobuf.ByteString
      getResponsemessageBytes();
}
