// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cms.proto

package com.zemoso.grpc.proto;

/**
 * Protobuf type {@code Logincms}
 */
public  final class Logincms extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Logincms)
    LogincmsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Logincms.newBuilder() to construct.
  private Logincms(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Logincms() {
    responsecode_ = 0;
    responsemessage_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Logincms(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            responsecode_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            responsemessage_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.zemoso.grpc.proto.Cms.internal_static_Logincms_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.zemoso.grpc.proto.Cms.internal_static_Logincms_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.zemoso.grpc.proto.Logincms.class, com.zemoso.grpc.proto.Logincms.Builder.class);
  }

  public static final int RESPONSECODE_FIELD_NUMBER = 1;
  private int responsecode_;
  /**
   * <code>int32 responsecode = 1;</code>
   */
  public int getResponsecode() {
    return responsecode_;
  }

  public static final int RESPONSEMESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object responsemessage_;
  /**
   * <code>string responsemessage = 2;</code>
   */
  public java.lang.String getResponsemessage() {
    java.lang.Object ref = responsemessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      responsemessage_ = s;
      return s;
    }
  }
  /**
   * <code>string responsemessage = 2;</code>
   */
  public com.google.protobuf.ByteString
      getResponsemessageBytes() {
    java.lang.Object ref = responsemessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      responsemessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (responsecode_ != 0) {
      output.writeInt32(1, responsecode_);
    }
    if (!getResponsemessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, responsemessage_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (responsecode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, responsecode_);
    }
    if (!getResponsemessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, responsemessage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.zemoso.grpc.proto.Logincms)) {
      return super.equals(obj);
    }
    com.zemoso.grpc.proto.Logincms other = (com.zemoso.grpc.proto.Logincms) obj;

    boolean result = true;
    result = result && (getResponsecode()
        == other.getResponsecode());
    result = result && getResponsemessage()
        .equals(other.getResponsemessage());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESPONSECODE_FIELD_NUMBER;
    hash = (53 * hash) + getResponsecode();
    hash = (37 * hash) + RESPONSEMESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getResponsemessage().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.zemoso.grpc.proto.Logincms parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zemoso.grpc.proto.Logincms parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zemoso.grpc.proto.Logincms parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zemoso.grpc.proto.Logincms parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zemoso.grpc.proto.Logincms parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zemoso.grpc.proto.Logincms parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zemoso.grpc.proto.Logincms parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zemoso.grpc.proto.Logincms parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zemoso.grpc.proto.Logincms parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.zemoso.grpc.proto.Logincms parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zemoso.grpc.proto.Logincms parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zemoso.grpc.proto.Logincms parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.zemoso.grpc.proto.Logincms prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Logincms}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Logincms)
      com.zemoso.grpc.proto.LogincmsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zemoso.grpc.proto.Cms.internal_static_Logincms_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zemoso.grpc.proto.Cms.internal_static_Logincms_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zemoso.grpc.proto.Logincms.class, com.zemoso.grpc.proto.Logincms.Builder.class);
    }

    // Construct using com.zemoso.grpc.proto.Logincms.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      responsecode_ = 0;

      responsemessage_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.zemoso.grpc.proto.Cms.internal_static_Logincms_descriptor;
    }

    @java.lang.Override
    public com.zemoso.grpc.proto.Logincms getDefaultInstanceForType() {
      return com.zemoso.grpc.proto.Logincms.getDefaultInstance();
    }

    @java.lang.Override
    public com.zemoso.grpc.proto.Logincms build() {
      com.zemoso.grpc.proto.Logincms result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.zemoso.grpc.proto.Logincms buildPartial() {
      com.zemoso.grpc.proto.Logincms result = new com.zemoso.grpc.proto.Logincms(this);
      result.responsecode_ = responsecode_;
      result.responsemessage_ = responsemessage_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.zemoso.grpc.proto.Logincms) {
        return mergeFrom((com.zemoso.grpc.proto.Logincms)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.zemoso.grpc.proto.Logincms other) {
      if (other == com.zemoso.grpc.proto.Logincms.getDefaultInstance()) return this;
      if (other.getResponsecode() != 0) {
        setResponsecode(other.getResponsecode());
      }
      if (!other.getResponsemessage().isEmpty()) {
        responsemessage_ = other.responsemessage_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.zemoso.grpc.proto.Logincms parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.zemoso.grpc.proto.Logincms) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int responsecode_ ;
    /**
     * <code>int32 responsecode = 1;</code>
     */
    public int getResponsecode() {
      return responsecode_;
    }
    /**
     * <code>int32 responsecode = 1;</code>
     */
    public Builder setResponsecode(int value) {
      
      responsecode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 responsecode = 1;</code>
     */
    public Builder clearResponsecode() {
      
      responsecode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object responsemessage_ = "";
    /**
     * <code>string responsemessage = 2;</code>
     */
    public java.lang.String getResponsemessage() {
      java.lang.Object ref = responsemessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responsemessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string responsemessage = 2;</code>
     */
    public com.google.protobuf.ByteString
        getResponsemessageBytes() {
      java.lang.Object ref = responsemessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responsemessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string responsemessage = 2;</code>
     */
    public Builder setResponsemessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      responsemessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string responsemessage = 2;</code>
     */
    public Builder clearResponsemessage() {
      
      responsemessage_ = getDefaultInstance().getResponsemessage();
      onChanged();
      return this;
    }
    /**
     * <code>string responsemessage = 2;</code>
     */
    public Builder setResponsemessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      responsemessage_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Logincms)
  }

  // @@protoc_insertion_point(class_scope:Logincms)
  private static final com.zemoso.grpc.proto.Logincms DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.zemoso.grpc.proto.Logincms();
  }

  public static com.zemoso.grpc.proto.Logincms getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Logincms>
      PARSER = new com.google.protobuf.AbstractParser<Logincms>() {
    @java.lang.Override
    public Logincms parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Logincms(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Logincms> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Logincms> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.zemoso.grpc.proto.Logincms getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

